version: '3'

services:
  app:
    build: ./
    networks:
    - default
    - localhost
    env_file:
    - .env
    environment:
    - VIRTUAL_HOST=${DOMAIN}
    - VIRTUAL_PORT=80
    - SKIP_CHOWN=1
    - PUID=1000
    - SSMTP_URI=ssmtp://mailcatcher:25
    - SSMTP_DEFAULT_FROM=info@docker.local
    volumes:
    - ./:/var/www/html:Z

networks:
  localhost:
    external: true
