version: '3'

services:
  web:
    build: ./
    networks:
    - default
    - proxy
    - dbaas
    env_file:
    - .env
    environment:
    - VIRTUAL_HOST=${DOMAIN}
    - VIRTUAL_PORT=80
    - SKIP_CHOWN=1
    - PUID=1000
    volumes:
    - ./:/var/www/html:Z

networks:
  proxy:
    external: true
  dbaas:
    external: true
